name: MacOS build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly
    - name: Install dependencies
      run: |
       rustup component add rust-src llvm-tools-preview
    - name: Build the kernel and bootloader for X86
      run: cargo kmake build --release --arch x86
    - name: Build kernel and bootloader for AArch64
      run: cargo kmake build --release --arch aarch64
    - name: Upload built image as artifact for X86
      uses: actions/upload-artifact@v2
      with:
        name: Phoenix X86
        path: ./build/x86_64/phoenix.img
    - name: Upload built image as artifact for AArch64
      uses: actions/upload-artifact@v2
      with:
        name: Phoenix AArch64
        path: ./build/aarch64/phoenix.img
